### ISSUE TITLE
Change JsonPropertyMapping.__init__ to avoid raising KeyErrors

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-json#10]
The following code taken from JsonPropertyMapping.__init__(..):

```
            if json_property_getter is None:
                def json_property_getter(obj_as_json: dict):
                    if optional and json_property_name not in obj_as_json:
                        return None
                    return obj_as_json[json_property_name]

```
doesn't prevent one for calling obj_as_json with a non-existing key, which is what happens with versions of baton previous to 0.16.1 and which results in a KeyError.
I think the return statement should  be changed to:
`
return obj_as_json.get(json_property_name)
`
But I am not sure if the calling code know how to handle None results for non-existing keys.

**Comment by colin-nolan** [comment]
I think the behaviour here is correct: if it has been defined that such JSON property exists (and maps to a property of the object), a key error should be raised if the property isn't there.

To get around the issue with the previous version of baton, it would be better to define the property (isit "replicate"?) as optional in the mapping. Then another mapping could be defined for the alternate JSON property name ("replicates"?). It is important to be aware though that the wrapper was not designed or tested with an older version of baton so other things may also be different!
