### ISSUE TITLE
Dump optional fields as null.

### ISSUE THREAD

**Issue by YuriIvanov** [wtsi-hgi/python-json#16]
Hello. I have one question. How can i dump optional fields as nulls using MappingJSONEecoderClassBuilder?

For example. I have class 

```
class UserInfo:
    def __init__(self):
        self.__id = None
        self.__full_name = None
        self.__avatar = None

    @property
    def id(self):
        return self.__id

    @id.setter
    def id(self, new_id):
        self.__id = new_id

    @property
    def full_name(self):
        return self.__full_name

    @full_name.setter
    def full_name(self, full_name):
        self.__full_name = full_name

    @property
    def avatar(self):
        return self.__avatar

    @avatar.setter
    def avatar(self, avatar):
        self.__avatar = avatar

_user_info_json_schema = [
    JsonPropertyMapping("Id", "id"),
    JsonPropertyMapping("FullName",
                        "full_name",
                        encoder_cls=UserFullNameJSONEncoder,
                        decoder_cls=UserFullNameJSONDecoder,
                        optional=True),
    JsonPropertyMapping("Avatar", "avatar",
                        encoder_cls=UserAvatarJSONEncoder,
                        decoder_cls=UserAvatarJSONDecoder,
                        optional=True)
]

UserInfoJSONDecoder = MappingJSONDecoderClassBuilder(UserInfo, _user_info_json_schema).build()
UserInfoJSONEncoder = MappingJSONEncoderClassBuilder(UserInfo, _user_info_json_schema).build()
```

And the code:
```
resp = requests.get(...)
user_info = json.loads(resp.text, cls=UserInfoJSONDecoder)
json.dumps(user_info, cls=UserInfoJSONEncoder)
```

If, for example, user_info.avatar is None json result does not contain that field at all. But i want that json result contain '"Avatar": null'. If i just remove optional flag, UserInfoJSONEncoder fails to parse json response that contains '"Avatar": null'.
How can i achieve this behaivor?

**Comment by colin-nolan** [comment]
The issue is that `UserAvatarJSONEncoder` is expecting a Python `object` (or list of them) so it falls over when it gets `None`.

I think it would be better if `None` is serialised to `null` and visa-versa for serialization; I shall submit a ticket for this change.

The (ugly) workaround for the moment would be to subclass the encoder and override `default`. If you change the name of the encoder that is built to `_UserAvatarJSONEncoder`:
```
class UserAvatarJSONEncoder(_UserAvatarJSONEncoder):
    def default(to_serialise):
       return None if to_serialise is None else super().default(to_serialise)
```
A similar workaround would be needed for the decoder (or it could be left with `optional=True` if the default value of "avatar" is None).

**Comment by colin-nolan** [comment]
This issue should be fixed as of version `1.4.0`. Does this solve your problem?

**Comment by YuriIvanov** [comment]
I think it should. But it need to be tested. Thanks anyway.

**Comment by YuriIvanov** [comment]
I updated to the newly version and remove optional flag. But it still raise same error.

`  File "/Users/RW/testing/workspace/repos/hgijson_test/hgijson_test.py", line 19, in <module>
    main()
  File "/Users/RW/testing/workspace/repos/hgijson_test/hgijson_test.py", line 16, in main
    print(json.dumps(user_info, cls=UserInfoJSONEncoder))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/builders.py", line 82, in default
    encoded = superclass.default(encoder, serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/_serialization.py", line 50, in default
    return serializer.serialize(serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/serialization.py", line 54, in serialize
    encoded_value = self._serialize_property_value(value, mapping.serializer_cls)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/serialization.py", line 68, in _serialize_property_value
    return serializer.serialize(to_serialize)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/_converters.py", line 37, in serialize
    return self._encoder.default(serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/builders.py", line 82, in default
    encoded = superclass.default(encoder, serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/_serialization.py", line 48, in default
    return super().default(serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: None is not JSON serializable`

**Comment by YuriIvanov** [comment]
[hgijson_test.zip](https://github.com/wtsi-hgi/python-json/files/401527/hgijson_test.zip)
Here is simple test project that i am using.

**Comment by YuriIvanov** [comment]
By the way, deserialization from null to None is working.
Problem with serialization to JSON.

**Comment by YuriIvanov** [comment]
And if you change (hgljson_test.py) user_info.avatar = None to user_info.avatar = UserAvatar() deserializer will correctly dumps inner None fields.

**Comment by colin-nolan** [comment]
`1.4.2` should fix the problem once and for all!

I've checked it against your test project and it works as expected :).

**Comment by YuriIvanov** [comment]
I've also checked inheritance and yes, it's now working without errors.
But i have one more question :) Now about optional flag behaivor.

What if i want that field in API response be optional, but in request it should be mandatory?
For example, Avatar field's optional flag set to True:
...
         "FullName": {
           "Firstname": "54030",
           "Lastname": "567727221715"
         },
         "Avatar": null,
         "IsValidPhoneNumber": false,
         "IsValidEmail": false
...
In this response Avatar is null and Decoder ignores it (in Avatar field will be value from constructor).
It's fine. But if i will encode Avatar field with optional flag set to True (same schema for request) and value None, Encoder just ignores that field (there is not such field in json at all).

**Comment by colin-nolan** [comment]
The best way to do this would be to allow the property to be optional but validate the value of `Avatar` in the input JSON. Chances are that, if you're forcing "Avatar" to be there, you don't want the property to be `null` so even if `optional_in=False, optional_out=True` existed, it wouldn't solve the problem. 

The below probably does what you're after:
```python
def validate_avatar(user_info_as_json: dict):
    avatar_as_json = user_info_as_json.get("Avatar")
    # If you actually want to allow `null`, change to `if "Avatar" in user_info_as_json` check
    if avatar_as_json is None:
        raise ValueError("A value for `Avatar` must be defined in input JSON")
    return avatar_as_json

_user_info_json_schema = [
    ...
    JsonPropertyMapping("Avatar", "avatar",
                        json_property_getter=validate_avatar,
                        encoder_cls=UserAvatarJSONEncoder,
                        decoder_cls=UserAvatarJSONDecoder, optional=True)
]
```

**Comment by YuriIvanov** [comment]
Ok. Thanks for the help.
