### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by JeffreyBouva** [wtsi-hgi/python-json#21]
Hi, 

When importing 

`from hgijson import (
    JsonPropertyMapping, MappingJSONEncoderClassBuilder,
    MappingJSONDecoderClassBuilder)`

I get an error:

`File "python3.5/site-packages/hgijson-3.0.0-py3.5.egg/hgijson/__init__.py", line 1, in <module>`
`File "python3.5/site-packages/hgijson-3.0.0-py3.5.egg/hgijson/json_converters/primitive.py", line 5, in <module>`
`ImportError: cannot import name 'Type'`
`Server with PID **** exited with code 1`

Also tried to install typing, but still getting this error

**Comment by colin-nolan** [comment]
Unfortunately I wasn't able to replicate the issue you encountered. The only issue I found in the codebase was some unused imports (including that of `Type`) in the `primitive.py` module. I have removed these and made a minor release `3.0.1`.

`Type` is part of the in-built `typing` package (https://docs.python.org/3/library/typing.html#typing.Type) and has been around since Python 3.5.2+ (no extra module install should be required). It looks like you're using Python 3.5 but perhaps you are using a pre 3.5.2 version?   

The last thing I can think of is that if you have a module in your own project named `typing`, this may be the problem as; in my experience, bad things can happen when naming collisions with the standard libraries occur!

**Comment by JeffreyBouva** [comment]
Hi Colin,

I’ve checked and I’m using 3.5.1 so that’s part of the issue, still great that you removed it if it was unused! I’m going to download your release tomorrow! Thank you very much for your fast response!

**Comment by JeffreyBouva** [comment]
Hi @colin-nolan ,

Not sure if you use Type in serialization.py, but it fails on Python 3.5.1
It's Unfortunate that your plugin isn't compatible with the 3.5.x but from 3.5.2, maybe a good idea to mention this in your docs. I will check if I can update my python version tonight ;) 

`File "/home/jeffrey/venv/packiq/lib/python3.5/site-packages/hgijson/serialization.py", line 2, in <module>`
`from typing import Any, Generic, Union, Dict, List, Optional, Iterable, Type, Callable`

**Comment by colin-nolan** [comment]
Yes, `Type` is used elsewhere I'm afraid.

I hate dealing with Python without type annotations, which look like they're only fully supported in 3.5.2; to support 3.5.x, the annotations would have to go, which would be a step backwards IMO. The projects I've been using the library in are all Python 3.6 so I've not worried about a lack of type hinting before. 

I will maintain support for the latest 3.5 release in addition to 3.6 (and beyond). I've added an issue to document the Python requirement.

**Comment by JeffreyBouva** [comment]
Cool, also a nice addition maybe.
I tried to make it work on 3.5.2 but that didn't work too, I now made my own solution.
Thanks for the great support, keep it up

FYI, error I got:

```from hgijson import (
   File "python3.5/site-packages/hgijson/__init__.py", line 5, in <module>
     from hgijson.json_converters.builders import MappingJSONDecoderClassBuilder, MappingJSONEncoderClassBuilder
   File "python3.5/site-packages/hgijson/json_converters/builders.py", line 5, in <module>
     from hgijson.json_converters.models import JsonPropertyMapping
   File "python3.5/site-packages/hgijson/json_converters/models.py", line 4, in <module>
     from hgijson.json_converters._converters import json_decoder_to_deserializer, json_encoder_to_serializer
   File "python3.5/site-packages/hgijson/json_converters/_converters.py", line 77, in <module>
     def json_encoder_to_serializer(encoder_cls: Union[Type[JSONEncoder], Callable[[], Type[JSONEncoder]]]) \\
   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
     dict(self.__dict__), parameters, _root=True)
   File "/usr/lib/python3.5/typing.py", line 512, in __new__
     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
   File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
     if super().__subclasscheck__(cls):
   File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
     for scls in cls.__subclasses__():
 TypeError: descriptor '__subclasses__' of 'type' object needs an argument```

**Comment by colin-nolan** [comment]
@JeffreyBouva sorry to hear it didn't work out for you.

Are you able to provide a sample of how you were using the library when you got this (e.g. the mapping and the builder)? Unfortunately I can't say what went wrong from the stacktrace (other than the library doesn't provide useful errors when it goes wrong!).
